using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using NVG = Notus.Variable.Globals;
using NVC = Notus.Variable.Constant;
using ND = Notus.Date;
namespace Notus.Validator
{
    public static class Helper
    {
        public static bool RightBlockValidator(Notus.Variable.Class.BlockData incomeBlock)
        {
            bool innerSendToMyChain=false;
            ulong queueTimePeriod = (ulong)(NVC.BlockListeningForPoolTime + NVC.BlockGeneratingTime + NVC.BlockDistributingTime);
            ulong blockTimeVal = ND.ToLong(incomeBlock.info.time);
            ulong blockGenarationTime = blockTimeVal - (blockTimeVal % queueTimePeriod);

            if (NVG.Settings.Nodes.Queue.ContainsKey(blockGenarationTime) == true)
            {
                string blockValidator = incomeBlock.validator.count.First().Key;
                /*
12:24:40.027 L1-Dev  -> Distributing [ ______________3 : 300 ] To
12:24:40.027 L1-Dev  -> <block> message sended
12:24:55.680 L1-Dev  -> NVG.Settings.WaitForGeneratedBlock = TRU
12:24:55.681 L1-Dev  -> Income Block Row No -> 4:NODBDuT7PTzAhdgB
12:24:55.682 L1-Dev  -> Income Block Row No -> 4, Validator => NO
12:24:56.001 L1-Dev  -> <block> Downloaded from other validator
blockGenarationTime : 20221107122455000
blockTimeVal        : 20221107122455050
NVG.NOW.Int         : 20221107122456001
blockValidator      : NODBDuT7PTzAhdgBecamFJa8hSpXR6SV49bvaKW
CurrentQueueTime    : 20221107122456000
NVG.Settings.Nodes.Queue[blockGenarationTime].Wallet) : NODHmAk7w
12:24:56.001 L1-Dev  -> That block generated by wrong validator
12:24:56.001 L1-Dev  -> Block Time : 202211071224550501028
12:24:56.001 L1-Dev  -> Please Wait While Node Terminating



                20221107122455500
                */
                Console.WriteLine("blockTimeVal        : " + blockTimeVal.ToString());
                Console.WriteLine("blockGenarationTime : " + blockGenarationTime.ToString());
                Console.WriteLine("blockValidator      : " + blockValidator);
                Console.WriteLine("NVG.Settings.Nodes.Queue[blockGenarationTime].Wallet) : " + NVG.Settings.Nodes.Queue[blockGenarationTime].Wallet);

                if (string.Equals(blockValidator, NVG.Settings.Nodes.Queue[blockGenarationTime].Wallet))
                {
                    innerSendToMyChain = true;
                }
            }
            else
            {
                Console.WriteLine("Time Does Not Have From Nodes List");

                Console.WriteLine("blockTimeVal : " + blockTimeVal.ToString() + " - " + incomeBlock.info.time);

                Console.WriteLine("Main.cs -> blockGenarationTime [ " +
                    incomeBlock.info.rowNo.ToString() +
                    " ]: " +
                    blockGenarationTime.ToString()
                );
                //Console.WriteLine(JsonSerializer.Serialize(NVG.Settings.Nodes.Queue, NVC.JsonSetting));
            }
            return innerSendToMyChain;
        }
    }
}
